Fix for Depreciated Code - MNIST Tutorial
Using "resample" in `RandomRotation(180., resample=Image.BILINEAR, expand=False)` throws a TypeError:
`TypeError: __init__() got an unexpected keyword argument 'resample'`

Hence requesting to update that line with the code below (which works!):
`RandomRotation(180., interpolation=InterpolationMode.BILINEAR, expand=False)`

Signed-off-by: Kartik Chincholikar <kartikchincholikar5@gmail.com>